### PR TITLE
reduce log level Receiver name missing

### LINKED ISSUE #149: Sound mode 7.1
As instructed in notes ... there is one unrecognized sound mode (on Marantz SR-7010):

`Not able to match sound mode: 'MULTI CH IN 7.1', returning raw sound mode.`

And of course - thank you very much for your perfect work on this library!

### PR DESCRIPTION
**Pull request by starkillerOG**
see the complaint in this issue about the warning that keeps showing up in the log while the warning is not that important: https://github.com/home-assistant/core/issues/37484

This will also close: https://github.com/scarface-4711/denonavr/issues/149

### CODE REVIEW

**Comment by starkillerOG** [comment]
~@scarface-4711 could you restart the test, I think it was just some random error of travis, the code looks good.~

**Comment by starkillerOG** [comment]
@scarface-4711 can you merge this?

**Comment by starkillerOG** [comment]
This also fixes https://github.com/scarface-4711/denonavr/issues/154

**Comment by starkillerOG** [comment]
@scarface-4711 could this be merged?
The travis error is unrelated to this PR and was already in the code

**Comment by ol-iver** [comment]
@starkillerOG sorry, I missed that on my vacation. I'll include it on Monday 😄

**Comment by ol-iver** [comment]
@starkillerOG thanks again 😄  It will be in the next version.

**Pull request merged**
