### PR TITLE
add sound mode "DOLBY PL2 GAME"

### PR DESCRIPTION
**Pull request by starkillerOG**
Reported in HomeAssistant issue here: https://github.com/home-assistant/core/issues/75403#issuecomment-1211156581

### CODE REVIEW

**Comment by starkillerOG** [comment]
@ol-iver could you merge this?

**Comment by starkillerOG** [comment]
@ol-iver could you merge this?
Maybe you could provide me with write acces to this library such that I can merge simple PRs like these myself?

**Comment by starkillerOG** [comment]
@ol-iver gentile reminder

**Comment by ol-iver** [comment]
Thanks 👍  
Let me see, what collaborator permissions could do 😄

**Pull request merged**
