### PR TITLE
Added AVR 2016 Sound Mode, All Zone Stereo, and Marantz SR6011-6013 support

### PR DESCRIPTION
**Pull request by andrewsayre**
Personally tested with a SR6012 model, but should also work for 6011 and 6013.  Sound mode does not work (as expected).

### CODE REVIEW

**Comment by andrewsayre** [comment]
@scarface-4711 would you be able to take a look at this?  Would love to get this merged and pushed to Home Assistant. =)

**Comment by skynet01** [comment]
Is this live? I have SR6013 and i can’t get it to work with HA, happy to test  things if you need help

**Comment by andrewsayre** [comment]
@skynet01 still waiting for this to be merged......  Feel free to test on your 6013!

**Comment by skynet01** [comment]
> @skynet01 still waiting for this to be merged...... Feel free to test on your 6013!
where would I merge this to in HA (sorry i am new to HA still) Is there a folder I can just go to and do "git pull" :)

**Comment by skynet01** [comment]
> > @skynet01 still waiting for this to be merged...... Feel free to test on your 6013!
> > where would I merge this to in HA (sorry I am new to HA still) Is there a folder I can just go to and do "git pull" :)

**Comment by ol-iver** [comment]
Thank you :)
I just created [HA pull request #18917](https://github.com/home-assistant/home-assistant/pull/18917) for these changes.

**Comment by andrewsayre** [comment]
Wohoo!  Thank you!

**Comment by skynet01** [comment]
Thank you!!

**Comment by tomdh76** [comment]
I have a Marantz SR7011 but denonavr is not working. Getting error 403. I have version 0.78 and I see that in the plugin port 8080 is stated. If i enter in my browser: http://IPMaratz :8080/goform/formMainZone_MainZoneXmlStatusLite.xml I get:
 a response

So it seems that there is a connection but I do not get info in HA.

**Pull request merged**
