### PR TITLE
Update README.md with spelling and grammar updates.  

### PR DESCRIPTION
**Pull request by prcutler**
Hi,

Thanks so much for maintaining the 'denonavr' library.  I use it both in Home Assistant and I'm building an app to run on my Raspberry Pi using it. 

I updated the README to fix a few small typos, added a link to the exceptions.py file and updated some sentences for better readability.

If you like the changes, I'll update the README.rst as well.

### CODE REVIEW

**Comment by prcutler** [comment]
I'm also working to refactor my Python app to use the new `async` calls.  I'd be happy to update the README with some examples of those as well if you're interested.  Thanks again!

**Comment by prcutler** [comment]
I've updated the README.md to also include the correct way to change the input (the old way) to address [Issue 216](https://github.com/scarface-4711/denonavr/issues/216) and it was also discussed in [Going Async PR #184](https://github.com/scarface-4711/denonavr/pull/184)

**Comment by ol-iver** [comment]
that's nice, thank you @prcutler 😄

**Comment by ol-iver** [comment]
More good examples are very welcome 👍

**Pull request merged**
